title: HK Blog
email: 2247han@gmail.com
description: 웹 개발자 강한결의 개발 블로그입니다.
author: hankyeolk
baseurl: ""
url: "https://dDDoublek.github.io"

# Social Profiles
github_username: hankyeolk
instagram_username: ddoublek.h
rocket_username: 2247han

# Add your google-analytics ID here to activate google analytics
# google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
